name: OWASP Dependency-Check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OWASP Dependency-Check
        run: |
          curl -s https://api.github.com/repos/jeremylong/DependencyCheck/releases/latest | jq -r '.assets[] | select(.name | test("dependency-check-.*-release.zip")) | .browser_download_url' | xargs curl -L -o dependency-check.zip
          unzip dependency-check.zip -d dependency-check
          chmod +x dependency-check/bin/dependency-check.sh

      - name: Run Dependency-Check
        run: |
          ./dependency-check/bin/dependency-check.sh --project "Gradle8-Scan" --scan . --format "ALL" --out reports --enableExperimental

      - name: Upload Dependency-Check Reports
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-reports
          path: reports/
