name: OWASP Dependency-Check
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OWASP Dependency-Check
        run: |
          curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/latest/download/dependency-check-${{ runner.os }}.zip
          unzip dependency-check.zip -d dependency-check
          chmod +x dependency-check/bin/dependency-check.sh

      - name: Run Dependency-Check
        run: |
          ./dependency-check/bin/dependency-check.sh --scan . --format "HTML" --out dependency-check-report.html --enableExperimental

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report.html
