name: OWASP Dependency-Check
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OWASP Dependency-Check
        run: |
          sudo apt-get update && sudo apt-get install jq -y
          curl -s https://api.github.com/repos/jeremylong/DependencyCheck/releases/latest | jq -r '.assets[] | select(.name | test("dependency-check-.*-release.zip")) | .browser_download_url' | xargs curl -L -o dependency-check.zip
          unzip -t dependency-check.zip
          unzip dependency-check.zip -d dependency-check
          chmod +x dependency-check/bin/dependency-check.sh

      - name: Run Dependency-Check
        run: |
          ./dependency-check/bin/dependency-check.sh --scan . --format "HTML" --out dependency-check-report.html --enableExperimental

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report.html
